---
plugins:     ./_plugins
title: CyberCrumbs
permalink: /:year/:title.html
url: http://cybercrumbs.net

markdown: rdiscount
pygments: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - readme.md
